[package]
name = "serverless-lando"
version = "0.1.0"
publish = false

[lib]
crate-type = ["cdylib"]
name = "lambda"

[dependencies]
cpython = "0.1"
envy = "0.3"
goji = "0.2"
lando = "0.1"
hubcaps = "0.4"
rust-crypto = "0.2"
serde = "1.0"
serde_derive = "1.0"