[package]
name = "jirabars"
version = "0.1.0"
publish = false
edition = "2018"

[dependencies]
envy = "0.4"
goji = "0.2"
hex = "0.3"
lambda_http = "0.1"
lambda_runtime = "0.2"
lazy_static = "1.3"
regex = "1.1"
reqwest = "0.9"
rust-crypto = "0.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"