service: jirabars
provider:
  name: aws
  runtime: python3.6
  stackTags:
    'mup:owner': 'platform-services'
    'mup:productName': '${self:service}'
  memorySize: 128
  environment:
    GITHUB_WEBHOOK_SECRET: '${env:GITHUB_WEBHOOK_SECRET}'
    JIRA_HOST: '${env:JIRA_HOST}'
    JIRA_USERNAME: '${env:JIRA_USERNAME}'
    JIRA_PASSWORD: '${env:JIRA_PASSWORD}'
    GITHUB_TOKEN: '${env:GITHUB_TOKEN}'
plugins:
  - serverless-rust
custom:
  rust:
    cargoFlags: '--features lando/python3-sys'
package:
  individually: true
  exclude:
    - ./**
functions:
  webhook:
    handler: liblambda.handler
    package:
      include:
        - liblambda.so
    events:
      - http:
          path: '/'
          method: POST