service: jirabars
provider:
  name: aws
  runtime: python3.6
  memorySize: 128
plugins:
  - serverless-rust
custom:
  rust:
    cargoFlags: '--features lando/python3-sys'
package:
  individually: true
  exclude:
    - ./**
functions:
  hello:
    handler: liblambda.handler
    package:
      include:
        - liblambda.so
    events:
      - http:
          path: '/'
          method: POST